# Generated by Django 3.0.7 on 2020-06-26 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='announcement',
            field=models.ForeignKey(blank=True, default=' ', on_delete=django.db.models.deletion.CASCADE, to='classroom.Announcement'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='assigment',
            field=models.ForeignKey(blank=True, default=' ', on_delete=django.db.models.deletion.CASCADE, to='classroom.Assigment'),
        ),
    ]
