# Generated by Django 3.0.7 on 2020-06-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_auto_20200626_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='subject',
        ),
        migrations.AddField(
            model_name='classroom',
            name='subject',
            field=models.ManyToManyField(to='classroom.Subject'),
        ),
    ]
