# Generated by Django 3.0.7 on 2020-06-27 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_auto_20200626_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='announcement',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='assigment',
        ),
        migrations.AddField(
            model_name='announcement',
            name='subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='classroom.Subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assigment',
            name='subject',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='classroom.Subject'),
            preserve_default=False,
        ),
    ]
