# Generated by Django 3.0.7 on 2020-06-28 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_auto_20200627_2026'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assigment',
            new_name='Assignment',
        ),
    ]
