# Generated by Django 3.0.7 on 2020-06-28 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_auto_20200628_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='subject',
        ),
    ]
